name: WebdriverIO
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Run wdio tests
      run: npm run run:all-test:headless
    - name: Generate allure-report
      run: npx allure generate allure-results --clean
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: allure
        path: allure-report/
    - name: Deploy to pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-report